# =============================================================================
# diagnose_site.R -- why are figures missing from the published site?
#
#     source("diagnose_site.R")
#
# Walks the whole chain in order and reports the first link that is broken.
# Takes a second. Run it before asking anyone else.
#
# THE CHAIN
#   1. scripts write PNGs        -> output/figures/
#   2. render_site.R copies them -> manuscript/figures/
#   3. render_site() copies that -> _site/figures/        <- the usual break
#   4. pages reference them      -> <img src="figures/x.png">
#   5. publish_site.sh pushes    -> gh-pages branch
# =============================================================================

root <- normalizePath(".", mustWork = TRUE)
ok <- function(t, l, n = "") cat(sprintf("  [%s] %-46s %s\n", if (t) "OK  " else "FAIL", l, n))
cat("\n--- site figure diagnosis ---\n\n")

# 1 -----------------------------------------------------------------------
f1 <- list.files(file.path(root, "output", "figures"), "[.]png$")
ok(length(f1) > 0, "1. PNGs exist in output/figures/",
   if (length(f1)) paste(length(f1), "files") else "run RUN_ALL.R")

# 2 -----------------------------------------------------------------------
f2 <- list.files(file.path(root, "manuscript", "figures"), "[.]png$")
ok(length(f2) > 0, "2. copied into manuscript/figures/",
   if (length(f2)) paste(length(f2), "files") else "run render_site.R")

# 3 -- the step that breaks when `figures` is in _site.yml's exclude list --
f3 <- list.files(file.path(root, "_site", "figures"), "[.]png$")
ok(length(f3) > 0, "3. copied into _site/figures/",
   if (length(f3)) paste(length(f3), "files")
   else "MOST LIKELY CAUSE: 'figures' is under exclude: in manuscript/_site.yml")

# 4 -----------------------------------------------------------------------
html <- list.files(file.path(root, "_site"), "[.]html$", full.names = TRUE)
if (!length(html)) {
  ok(FALSE, "4. pages reference images", "no HTML in _site/ -- run render_site.R")
} else {
  pat <- "src=\"[^\"]+[.](png|jpg|jpeg|gif|svg)\""
  src <- unique(unlist(lapply(html, function(h) {
    x <- paste(readLines(h, warn = FALSE), collapse = " ")
    gsub("^src=\"|\"$", "", regmatches(x, gregexpr(pat, x))[[1]])
  })))
  src <- src[!grepl("^(https?:|data:)", src)]
  bad <- src[!file.exists(file.path(root, "_site", src))]
  ok(length(src) > 0, "4. pages reference images", paste(length(src), "references"))
  ok(length(bad) == 0, "   all references resolve inside _site/",
     if (length(bad)) paste(length(bad), "broken, e.g.", bad[1]) else "")
  # which pages carry figures at all
  cat("\n  figures per page:\n")
  for (h in html) {
    x <- paste(readLines(h, warn = FALSE), collapse = " ")
    n <- length(regmatches(x, gregexpr(pat, x))[[1]])
    cat(sprintf("    %-34s %d\n", basename(h), n))
  }
  cat("\n  index.html having 0 is CORRECT -- it is a text overview page.\n")
}

# 4b -- pages in _site/ that no longer have a source ------------------------
# render_site() does not delete stale output, so a renamed or newly excluded
# page is published forever. GITHUB_PAGES.html surviving after *.md was excluded
# is exactly this.
if (length(html)) {
  # site_*.Rmd are generated by render_site.R and are legitimate sources.
  src_pages <- sub("[.]Rmd$", "", list.files(file.path(root, "manuscript"), "[.]Rmd$"))
  out_pages <- sub("[.]html$", "", basename(html))
  orphan <- setdiff(out_pages, src_pages)
  # An orphan is EITHER stale output OR a stray document in manuscript/ that is
  # being rendered as a page. Distinguish them, because the fixes differ.
  # Skip "_" files: render_site() never renders them, so they cannot be strays.
  found <- basename(list.files(file.path(root, "manuscript"), "[.](Rmd|md)$"))
  found <- found[!grepl("^_", found)]
  stray <- setdiff(found[!grepl("^site_.*[.]Rmd$", found)],
                   c("index.Rmd", "methods.Rmd", "results.Rmd",
                     "results_among_sites.Rmd"))
  note <- if (!length(orphan)) "" else if (length(stray))
    paste0("orphaned: ", paste(orphan, collapse = ", "),
           " -- source still in manuscript/: ", paste(stray, collapse = ", "),
           ". Delete or move it; `exclude:` cannot stop it rendering.")
  else
    paste0("orphaned: ", paste(orphan, collapse = ", "),
           " -- stale output; the new render_site.R cleans _site/ first.")
  ok(length(orphan) == 0, "4b. every page in _site/ has a source .Rmd", note)
}

# 5 -----------------------------------------------------------------------
ok(file.exists(file.path(root, "_site", ".nojekyll")), "5. _site/.nojekyll present",
   "without it GitHub Pages drops folders beginning with _")

# --- the two configuration traps, checked directly ---------------------------
yml <- file.path(root, "manuscript", "_site.yml")
if (file.exists(yml)) {
  yl <- readLines(yml, warn = FALSE)
  i <- grep("^\\s*exclude\\s*:", yl)
  bad <- FALSE
  if (length(i)) {
    blk <- yl[(i[1] + 1):length(yl)]
    blk <- blk[seq_len(max(0, which(!grepl("^\\s*-", blk))[1] - 1))]
    bad <- any(grepl("figures", blk))
  }
  ok(!bad, "6. _site.yml does NOT exclude `figures`",
     if (bad) "REMOVE that line -- it is why step 3 failed" else "")
}

cat("\n  If every check passes and the live site still has no images, the published\n")
cat("  branch is stale: re-run  bash publish_site.sh  and hard-refresh the browser.\n\n")
